installer: ensure sysconfig.txt is installed
The error came in very late, in rpmbuild:

	Processing files: zarafa-7.2.1.1449432494.3409a09-5.1.x86_64
	error: File not found: /home/abuild/rpmbuild/BUILDROOT/zarafa-7.2.1.1449432494.3409a09-5.1.x86_64/var/adm/fillup-templates/sysconfig.zarafa

The mv command failed, but because of the ||true, it did not fail
during `make install` — but should have.