common: use proper include path for my_getopt.h
Compile error on certain platforms, because MySQL polluted the
namespace :-/

In file included from ../../common/my_getopt.cpp:3:0:
/usr/include/mysql/my_getopt.h:22:24:
fatal error: my_default.h: No such file or directory