treewide: resolve c++11-narrowing warnings of clang
/usr/include/c++/5/bits/stl_bvector.h:548:31: note:
ECTableManager.cpp:103:80: error: non-constant-expression cannot be
narrowed from type 'unsigned int' to 'int' in initializer list
[-Wc++11-narrowing]
struct propTagArray sPropTagArrayContents =
 { (unsigned int *)&sContentsProps, arraySize(sContentsProps)};
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~

Replace the use of arraySize by ARRAY_SIZE, which is a variant with
constant expression property.