pyza: restore internal use of typedefs
Issue was introduced by bp/zcp/7.2.3-180-g54bb8e7, caused mapi_wrap.cxx
to look different and behave different:
TypeError: IECServiceAdmin_GetUser() takes exactly 4 arguments (3 given).